version: '3.8'

services:
  mysql:
    image: mysql:8.0.28
    container_name: zenith-mysql
    environment:
      MYSQL_ROOT_PASSWORD: qwe123
      MYSQL_DATABASE: zenith
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - zenith-network

  app:
    build: .
    container_name: zenith-app
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/zenith?useSSL=false
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: qwe123
    ports:
      - "8080:8080"
    networks:
      - zenith-network

networks:
  zenith-network:
    driver: bridge

volumes:
  mysql-data:
